contact_links:
  - name: Ask a question
    url: https://github.com/brilla-cx/web/discussions
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/brilla-cx/web/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
